---
abstract: "Perl Application Development and Refactoring Environment\r"
author:
  - 'Gabor Szabo'
build_requires:
  ExtUtils::MakeMaker: 6.11
  Test::Compile: 0.08
  Test::Exception: 0.27
  Test::More: 0.47
  Test::NoWarnings: 0.084
  Test::Script: 1.03
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Padre
no_index:
  directory:
    - t
    - xt
    - eg
    - share
    - inc
    - privinc
    - share
    - share
    - inc
    - t
requires:
  App::Ack: 1.86
  Carp: 0
  Class::Adapter: 1.05
  Class::Autouse: 1.26
  Class::Unload: 0.03
  Class::XSAccessor: 0.14
  Cwd: 3.2701
  DBD::SQLite: 1.10
  DBI: 1.58
  Data::Dumper: 0
  Devel::Dumpvar: 0.04
  Digest::MD5: 0
  Encode: 2.26
  File::Basename: 0
  File::Copy::Recursive: 0.37
  File::Find::Rule: 0.30
  File::HomeDir: 0.82
  File::ShareDir: 1.00
  File::ShareDir::PAR: 0.03
  File::Spec: 3.2701
  File::Spec::Functions: 3.2701
  File::Which: 0.05
  FindBin: 0
  Getopt::Long: 0
  HTML::Entities: 3.57
  HTML::Parser: 3.58
  IO::Scalar: 0
  IO::Socket: 1.30
  IO::String: 1.08
  IPC::Cmd: 0.42
  IPC::Open3: 0
  List::Util: 1.18
  Module::Inspector: 0.04
  Module::Refresh: 0.13
  Module::Starter: 1.50
  ORLite: 1.17
  ORLite::Migrate: 0.01
  PAR: 0.970
  PPI: 1.203
  Params::Util: 0.33
  Parse::ErrorString::Perl: 0.11
  Pod::POM: 0.17
  Pod::Simple: 3.07
  Pod::Simple::XHTML: 3.04
  Probe::Perl: 0.01
  Storable: 2.15
  Term::ReadLine: 0
  Text::Diff: 0.35
  Text::FindIndent: 0.03
  Thread::Queue: 2.11
  URI: 0
  Wx: 0.89
  Wx::Perl::Dialog: 0.04
  Wx::Perl::ProcessStream: 0.11
  YAML::Tiny: 1.32
  perl: 5.008001
  threads: 1.71
  threads::shared: 1.26
resources:
  bugtracker: http://padre.perlide.org/
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre/
version: 0.25
