---
name: Padre
version: 0.06
author:
  - Gabor Szabo
abstract: Perl Application Development and Refactoring Environment
license: perl
resources:
  Repository: http://svn.perlide.org/padre
  bugtracker: http://padre.perlide.org/
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Class::Accessor: 0
  Class::Autouse: 1.26
  Cwd: 0
  DBD::SQLite: 0
  DBI: 0
  Data::Dumper: 0
  File::Copy::Recursive: 0
  File::HomeDir: 0
  File::ShareDir: 1.00
  File::Slurp: 0
  File::Spec::Functions: 0
  FindBin: 0
  Getopt::Long: 0
  IO::Socket: 0
  List::Util: 0
  Module::Inspector: 0.04
  ORLite: 0.10
  Pod::POM: 0
  Pod::Simple: 0
  Probe::Perl: 0.01
  Term::ReadLine: 0
  Wx: 0
  Wx::Perl::ProcessStream: 0
  YAML::Tiny: 1.32
  perl: 5.008
build_requires:
  Test::Exception: 0
  Test::More: 0.47
  Test::NoWarnings: 0
provides:
  Padre:
    file: lib/Padre.pm
    version: 0.06
  Padre::Config:
    file: lib/Padre/Config.pm
    version: 0.06
  Padre::DB:
    file: lib/Padre/DB.pm
    version: 0.06
  Padre::Demo:
    file: lib/Padre/Demo.pm
    version: 0.06
  Padre::Demo::Frame:
    file: lib/Padre/Demo/Frame.pm
    version: 0.06
  Padre::Pod::Frame:
    file: lib/Padre/Pod/Frame.pm
    version: 0.06
  Padre::Pod::Indexer:
    file: lib/Padre/Pod/Indexer.pm
    version: 0.06
  Padre::Pod::Viewer:
    file: lib/Padre/Pod/Viewer.pm
    version: 0.06
  Padre::Pod::Viewer::POD:
    file: lib/Padre/Pod/Viewer.pm
  Padre::Pod::Viewer::View:
    file: lib/Padre/Pod/Viewer.pm
  Padre::Project:
    file: lib/Padre/Project.pm
    version: 0.06
  Padre::Wx::App:
    file: lib/Padre/Wx/App.pm
    version: 0.06
  Padre::Wx::FindDialog:
    file: lib/Padre/Wx/FindDialog.pm
    version: 0.06
  Padre::Wx::MainWindow:
    file: lib/Padre/Wx/MainWindow.pm
    version: 0.06
  Padre::Wx::Popup:
    file: lib/Padre/Wx/Popup.pm
    version: 0.06
  Padre::Wx::Text:
    file: lib/Padre/Wx/Text.pm
    version: 0.06
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - t
    - eg
    - share
