---
abstract: 'Perl Application Development and Refactoring Environment'
author:
  - 'Gabor Szabo'
build_requires:
  Capture::Tiny: 0.06
  ExtUtils::MakeMaker: 6.42
  Locale::Msgfmt: 0.14
  Test::Exception: 0.27
  Test::More: 0.88
  Test::NoWarnings: 0.084
  Test::Script: 1.05
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
keywords:
  - auto-completion
  - code
  - coding
  - completion
  - context
  - cross-platform
  - development
  - editor
  - environment
  - find
  - 'function list'
  - gui
  - help
  - highlight
  - hightlighting
  - ide
  - linux
  - 'mac os'
  - 'mac os x'
  - padre
  - perl
  - portable
  - refactoring
  - replace
  - syntax
  - windows
  - wx
  - wxwidgets
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Padre
no_index:
  directory:
    - eg
    - inc
    - privinc
    - share
    - t
    - xt
requires:
  App::Ack: 1.86
  Carp: 0
  Class::Adapter: 1.05
  Class::Unload: 0.03
  Class::XSAccessor: 1.05
  Cwd: 3.2701
  DBD::SQLite: 1.10
  DBI: 1.58
  Data::Dumper: 0
  Debug::Client: 0.11
  Devel::Dumpvar: 0.04
  Devel::Refactor: 0.05
  Digest::MD5: 0
  Encode: 2.26
  ExtUtils::Manifest: 1.56
  File::Basename: 0
  File::Copy::Recursive: 0.37
  File::Find::Rule: 0.30
  File::Glob: 0
  File::HomeDir: 0.84
  File::Next: 1.06
  File::Path: 2.07
  File::Remove: 1.42
  File::ShareDir: 1.00
  File::Spec: 3.2701
  File::Spec::Functions: 3.2701
  File::Temp: 0
  File::Which: 1.08
  FindBin: 0
  Format::Human::Bytes: 0
  Getopt::Long: 0
  HTML::Entities: 3.57
  HTML::Parser: 3.58
  IO::Scalar: 2.110
  IO::Socket: 1.30
  IO::String: 1.08
  IPC::Open2: 0
  IPC::Open3: 0
  List::MoreUtils: 0.22
  List::Util: 1.18
  Module::CoreList: 0
  Module::Refresh: 0.13
  Module::Starter: 1.50
  ORLite: 1.20
  ORLite::Migrate: 0.03
  POSIX: 0
  PPI: 1.205
  PPIx::EditorTools: 0.09
  Params::Util: 0.33
  Parse::ErrorString::Perl: 0.11
  Parse::ExuberantCTags: 1.00
  Pod::Abstract: 0.16
  Pod::Functions: 0
  Pod::POM: 0.17
  Pod::Perldoc: 3.15
  Pod::Simple: 3.07
  Pod::Simple::XHTML: 3.04
  Probe::Perl: 0.01
  Storable: 2.15
  Template::Tiny: 0.03
  Term::ReadLine: 0
  Text::Balanced: 0
  Text::Diff: 0.35
  Text::FindIndent: 0.05
  Thread::Queue: 2.11
  URI: 0
  Wx: 0.91
  Wx::Perl::ProcessStream: 0.20
  YAML::Tiny: 1.32
  perl: 5.008005
  pip: 0.13
  threads: 1.71
  threads::shared: 1.26
  version: 0
resources:
  bugtracker: http://padre.perlide.org/trac/
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre/
version: 0.53
